#ifndef _CONFIG_H
#define _CONFIG_H

#define BLYNK_TEMPLATE_ID "TMPL2Jty3Fvb2"
#define BLYNK_TEMPLATE_NAME "Watering Plant"

#define WIFI_SSID "WE_E25B3B"
#define WIFI_PASSWORD "vodafone01097674852"
#define BLYNK_AUTH_TOKEN "OAChabC0opH-P6y5YsIEYix0DLfsh23h"

#define DEBUG_MODE
#define SERIAL_BAUD_RATE 115200

#define DELAY_CONNECTION 500
#define SOIL_MOISTURE_TIME 3000
#define WATER_LEVEL_TIME 3000
#define PUMB_BUTTON_DELAY 250

#define SOUND_SPEED 0.0343
#define MAX_DISTANCE 0
#define DISTANCE_TO_BOTTON 100
#define CRITICAL_SOIL_MOISTURE 20
#define CRITICAL_WATER_LEVEL 20

#define SIGNAL_HIGH_TIME 10
#define SIGNAL_LOW_TIME 2

#endif